spring:
  application:
    name: mail-service
  config:
    import: optional:docker.env[.properties]

  #Email
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USER}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  #Kafka
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:9092

server:
  port: 0

eureka:
  client:
    service-host: ${EUREKA_HOST}
    service-url:
      defaultZone: http://${eureka.client.service-host}:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}
    hostname: ${EUREKA_HOST}