spring:
  application:
    name: mail-service
  config:
    import: optional:docker.env[.properties]

  #Email
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USER}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  #Kafka
  kafka:
    bootstrap-servers: ${MAIN_HOST}:9092
