name: Docker Image CI

on:
  push:
    branches: [ "*master" ]
  pull_request:
    branches: [ "*master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Build
        uses: docker/setup-buildx-action@v2
      -
        name: Build with Maven
        run: mvn wrapper:wrapper -Dmaven=3.9.0
      -
        name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/mail-service
          tags: 0.1.1
          registry: docker.io
          dockerfile: Dockerfile
          target: production
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  deployment:
    needs: build
    runs-on:
      - self-hosted
      - mail-service-k8s
    steps:
      - name: Rollout restart
        run: |
          set -ex
          cd $HOME
          wget https://dl.k8s.io/release/v1.26.0/bin/linux/arm64/kubectl
          chmod +x ./kubectl
          ~/kubectl rollout restart deployment mail-service-v1 -n default
